In [2]:
import pandas as pd
 
def main():
 
    # List of Tuples
    empoyees = [('jack', 34, 'Sydney', 5) ,
               ('Riti', 31, 'Delhi' , 7) ,
               ('Aadi', 16, 'New York', 11)
                ]
 
    # Create a DataFrame object
    empDfObj = pd.DataFrame(empoyees, columns=['Name', 'Age', 'City', 'Experience'], index=['a', 'b', 'c'])
    print("Contents of the Dataframe : ")
    print(empDfObj)
 
    print('**** Iterate over rows in a dataframe using Dataframe.iterrows() ****')
 
    # Yields a tuple of index label and series for each row in the datafra,e
    for (index_label, row_series) in empDfObj.iterrows():
       print('Row Index label : ', index_label)
       print('Row Content as Series : ', row_series.values)
 
    print('**** Iterate over rows in dataframe using Dataframe.itertuples() ****')
 
    print('All rows of Dataframe as named tuple :')
 
    # Iterate over the Dataframe rows as named tuples
    for namedTuple in empDfObj.itertuples():
       #Print row contents inside the named tuple
       print(namedTuple)
 
 
    print('All rows of Dataframe ( without index column values) as named tuple :')
 
    # Iterate over the Dataframe rows as named tuples without index
    for namedTuple in empDfObj.itertuples(index=False):
       # Print row contents inside the named tuple
       print(namedTuple)
 
    print('All rows of Dataframe as named tuple with custom name  "Employee" :')
 
    # Give Custom Name to the tuple while Iterating over the Dataframe rows
    for row in empDfObj.itertuples(name='Employee'):
       # Print row contents inside the named tuple
       print(row)
 
    print('**** Iterate over rows in dataframe as dictionary using Dataframe.itertuples() ****')
 
    # itertuples() yields an iterate to named tuple
    for row in empDfObj.itertuples(name='Employee'):
       # Convert named tuple to dictionary
       dictRow = row._asdict()
       # Print dictionary
       print(dictRow)
       # Access elements from dict i.e. row contents
       print(dictRow['Name'] , ' is from ' , dictRow['City'])
 
 
 
    print('**** Iterate over rows in dataframe using index position ****')
 
    # Loop through rows of dataframe by index i.e. from 0 to number of rows
    for i in range(0, empDfObj.shape[0]):
       # get row contents as series using iloc{] and index position of row
       rowSeries = empDfObj.iloc[i]
       # print row contents
       print(rowSeries.values)
 
    print('**** Iterate over rows in dataframe in reverse order using index position ****')
 
    # Loop through rows of dataframe by index in reverse i.e. from last row to row at 0th index.
    for i in range(empDfObj.shape[0] - 1, -1, -1):
       # get row contents as series using iloc{] and index position of row
       rowSeries = empDfObj.iloc[i]
       # print row contents
       print(rowSeries.values)
 
 
    print('**** Iterate over rows in dataframe using index labels ****')
 
    # loop through all the names in index label sequence of dataframe
    for index in empDfObj.index:
       # For each index label, access the row contents as series
       rowSeries = empDfObj.loc[index]
       # print row contents
       print(rowSeries.values)
 
    print('**** Update contents a dataframe While iterating row by row ****')
 
    print('Create a New dataframe')
 
    # List of Tuples
    salaries = [(11, 5, 70000, 1000) ,
               (12, 7, 72200, 1100) ,
               (13, 11, 84999, 1000)
               ]
 
    # Create a DataFrame object
    salaryDfObj = pd.DataFrame(salaries, columns=['ID', 'Experience' , 'Salary', 'Bonus'])
    print("Contents of the Dataframe : ")
    print(salaryDfObj)
 
    print('Multiply values in Bonus column by 2 while iterating over the datafarme')
 
    # iterate over the dataframe row by row
    for index_label, row_series in salaryDfObj.iterrows():
       # For each row update the 'Bonus' value to it's double
       salaryDfObj.at[index_label , 'Bonus'] = row_series['Bonus'] * 2
 
    print("Contents of the Modified Dataframe : ")
    print(salaryDfObj)
 
if __name__ == '__main__':
  main()

Contents of the Dataframe :
   Name  Age      City  Experience
a  jack   34    Sydney           5
b  Riti   31     Delhi           7
c  Aadi   16  New York          11
**** Iterate over rows in a dataframe using Dataframe.iterrows() ****
Row Index label :  a
Row Content as Series :  ['jack' 34 'Sydney' 5]
Row Index label :  b
Row Content as Series :  ['Riti' 31 'Delhi' 7]
Row Index label :  c
Row Content as Series :  ['Aadi' 16 'New York' 11]
**** Iterate over rows in dataframe using Dataframe.itertuples() ****
All rows of Dataframe as named tuple :
Pandas(Index='a', Name='jack', Age=34, City='Sydney', Experience=5)
Pandas(Index='b', Name='Riti', Age=31, City='Delhi', Experience=7)
Pandas(Index='c', Name='Aadi', Age=16, City='New York', Experience=11)
All rows of Dataframe ( without index column values) as named tuple :
Pandas(Name='jack', Age=34, City='Sydney', Experience=5)
Pandas(Name='Riti', Age=31, City='Delhi', Experience=7)
Pandas(Name='Aadi', Age=16, City='New York', Experience=11)
All rows of Dataframe as named tuple with custom name  "Employee" :
Employee(Index='a', Name='jack', Age=34, City='Sydney', Experience=5)
Employee(Index='b', Name='Riti', Age=31, City='Delhi', Experience=7)
Employee(Index='c', Name='Aadi', Age=16, City='New York', Experience=11)
**** Iterate over rows in dataframe as dictionary using Dataframe.itertuples() ****
OrderedDict([('Index', 'a'), ('Name', 'jack'), ('Age', 34), ('City', 'Sydney'), ('Experience', 5)])
jack  is from  Sydney
OrderedDict([('Index', 'b'), ('Name', 'Riti'), ('Age', 31), ('City', 'Delhi'), ('Experience', 7)])
Riti  is from  Delhi
OrderedDict([('Index', 'c'), ('Name', 'Aadi'), ('Age', 16), ('City', 'New York'), ('Experience', 11)])
Aadi  is from  New York
**** Iterate over rows in dataframe using index position ****
['jack' 34 'Sydney' 5]
['Riti' 31 'Delhi' 7]
['Aadi' 16 'New York' 11]
**** Iterate over rows in dataframe in reverse order using index position ****
['Aadi' 16 'New York' 11]
['Riti' 31 'Delhi' 7]
['jack' 34 'Sydney' 5]
**** Iterate over rows in dataframe using index labels ****
['jack' 34 'Sydney' 5]
['Riti' 31 'Delhi' 7]
['Aadi' 16 'New York' 11]
**** Update contents a dataframe While iterating row by row ****
Create a New dataframe
Contents of the Dataframe :
   ID  Experience  Salary  Bonus
0  11           5   70000   1000
1  12           7   72200   1100
2  13          11   84999   1000
Multiply values in Bonus column by 2 while iterating over the datafarme
Contents of the Modified Dataframe :
   ID  Experience  Salary  Bonus
0  11           5   70000   2000
1  12           7   72200   2200
2  13          11   84999   2000